In [1]:
import numpy as np


In [4]:
a= np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray

In [14]:
c= np.array([1.2, 2.5, 5.1])
c.dtype

dtype('float64')

In [6]:
a=np.arange(6)
print(a)


[0 1 2 3 4 5]


In [8]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
c=np.arange(24).reshape(3, 4, 2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [10]:
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [11]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [ ]:
"Basic operations"


In [12]:
a=np.array([20, 30, 40, 50])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [14]:
c = a - b
c

array([20, 29, 38, 47])

In [15]:
b**2


array([0, 1, 4, 9])

In [16]:
a**2

array([ 400,  900, 1600, 2500])

In [17]:
10*np.sin(b)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [3]:
np.empty((2, 3))


array([[4.67540153e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [4]:
from numpy import pi
x = np.linspace(0, 2*pi, 100)
y= np.sin(x)

In [2]:
a= np.array([20, 30, 40, 50])
b= np. arange(4)
b

array([0, 1, 2, 3])

In [3]:
c= a - b
c

array([20, 29, 38, 47])

In [4]:
b**2

array([0, 1, 4, 9])

In [5]:
10*np.sin(b)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [6]:
a< 35

array([ True,  True, False, False])

In [5]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

a *= 3

a

array([[3, 3, 3],
       [3, 3, 3]])

In [6]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [8]:
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name


'float64'

In [11]:
a

array([1, 1, 1], dtype=int32)

In [12]:
b

array([0.        , 1.57079633, 3.14159265])

In [14]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [15]:
c.dtype.name


'float64'

In [17]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [18]:
e = np.exp(a*1j)
e

array([0.54030231+0.84147098j, 0.54030231+0.84147098j,
       0.54030231+0.84147098j])

In [19]:
d.dtype.name

'complex128'

In [20]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [21]:
a.sum()


3.1057109529998157

In [22]:
a.min()


0.027559113243068367

In [23]:
a.max()


0.8277025938204418

In [24]:
a.sum(axis=0)

array([0.85526171, 1.16271225, 1.087737  ])

In [25]:
a.sum(axis=1)

array([1.78649542, 1.31921554])

In [26]:
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [27]:
b.sum(axis=0)

4.71238898038469

In [28]:
b

array([0.        , 1.57079633, 3.14159265])

In [32]:
a=np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [34]:
a.sum(axis=1)

array([ 6, 22, 38])

In [2]:
a = np.arange(12)**2
i = np.array([1, 1, 2, 3, 4])

a[i]

array([ 1,  1,  4,  9, 16])

In [4]:
i

array([1, 1, 2, 3, 4])

In [6]:
j = np.array([[2, 3], [5, 8]])

a[j]


array([[ 4,  9],
       [25, 64]])

In [7]:
pallete = np.array([[0, 0, 0],
                   [225, 0, 0],
                   [0, 225, 0],
                   [0, 0, 225],
                    [225, 225, 225]
                   ])
image = np.array([[0, 1, 2, 0], 
                 [0, 3, 4, 0]])

pallete[image]

array([[[  0,   0,   0],
        [225,   0,   0],
        [  0, 225,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 225],
        [225, 225, 225],
        [  0,   0,   0]]])

In [8]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
i = np.array([[0, 1], [1, 2]])
i

array([[0, 1],
       [1, 2]])